#!/bin/sh
# Starts programs only if they aren't already running

# Not mine, props to Boo#3642 (from unixporn disord)
# ---{{{

start() {
    COMMAND=$1
    shift
    ARGS=$*
    pgrep -u "$USER" -ic "$COMMAND" > /dev/null || $COMMAND $ARGS &
}

termstart() {
    COMMAND=$1
    shift
    ARGS=$*
    pgrep -u "$USER" -ic "$COMMAND" > /dev/null || st -n $COMMAND $COMMAND $ARGS &
}

# ---}}}

# Phisch's Picom -> Transitions
start ~/.bin/phicom
# Disable System Bell
start xset -b
# Set Wallpaper
start feh --bg-tile /home/javacafe01/Pictures/wallpapers/1.png
