# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/405c9c72-5d5f-4a5f-9fe0-646726626b48";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/CC2A-A186";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/97d9b22d-cfd8-4ff1-a15c-f1493c6a7049"; }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
