#!/bin/bash

## WM Name
id_bloat=$(xprop -root _NET_SUPPORTING_WM_CHECK)
id=${id_bloat##* }
wm_bloat=$(xprop -id "$id" _NET_WM_NAME)

## Get system info
#user="${USER}@$(hostname)"
distro=$(. /etc/{os-release,*-release,*_version} ; echo "${ID}")
#kernel="$(uname -sr | sed 's/-.*//')"
#uptime="$(uptime -p | sed 's/up //')"
shell="$(basename ${SHELL})"
packages="$(pacman -Qq | wc -l)"
wm="$(echo $wm_bloat | cut -d'"' -f 2)"
term="$(pstree -As $$ | awk -F "---" '{print $2}')"


## Define Colours
if [[ $1 = "--red" ]]; then
    bgaccent="$(tput setab 1)"
    accent="$(tput setaf 1)"
elif [[ $1 = "--green" ]]; then
    bgaccent="$(tput setab 2)"
    accent="$(tput setaf 2)"
elif [[ $1 = "--yellow" ]]; then
    bgaccent="$(tput setab 3)"
    accent="$(tput setaf 3)"
elif [[ $1 = "--blue" ]]; then
    bgaccent="$(tput setab 4)"
    accent="$(tput setaf 4)"
elif [[ $1 = "--magenta" ]]; then
    bgaccent="$(tput setab 5)"
    accent="$(tput setaf 5)"
elif [[ $1 = "--cyan" ]]; then
    bgaccent="$(tput setab 6)"
    accent="$(tput setaf 6)"
else
    bgaccent="$(tput setab 1)"
    accent="$(tput setaf 1)"
fi

bold="$(tput bold)"
#white="$(tput setab 7)$(tput setaf 8)"
blue_oof="$(tput setab 4)$(tput setaf 8)"
white="$(tput setaf 7)"
yellow="$(tput setaf 12)"
red="$(tput setaf 1)"
blue="$(tput setaf 4)"
green="$(tput setaf 2)"
orange="$(tput setaf 8)"
violet="$(tput setaf 5)"
cyan="$(tput setaf 6)"
reset="$(tput sgr0)"
cbg="${reset}${bold}${bgaccent}${white}"
cr="${reset}"
c0="${reset}${bold}"
c1="${reset}${accent}"

## Output

cat <<EOF

${c0}${cyan}      ----      ${c0}${blue}${c0}${yellow}  ${reset}${c0}${blue}  ${cr}${white}${distro}${reset} 
${c0}${cyan}     / O O\     ${c0}${blue}${c0}${yellow} 缾${reset}${c0}${blue}  ${cr}${white}${wm}${reset}
${c0}${cyan}    |      |    ${c0}${blue}${c0}${yellow}  ${reset}${c0}${blue}  ${cr}${white}${term}${reset}
${c0}${cyan}    |/\/\/\|    ${c0}${blue}${c0}${yellow}  ${reset}${c0}${blue}  ${cr}${white}${packages}${reset}
${c0}${orange}   ----------   ${c0}${blue}${c0}${yellow}  ${reset}${c0}${blue}  ${cr}${white}${shell}${reset}
EOF

f=3 b=4
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
d=$'\e[1m'
t=$'\e[0m'
v=$'\e[7m'
 
 
#pcs() { for i in {0..7}; do echo -en "\e[${1}$((30+$i))m\u2584 \e[0m"; done; }
#printf "\n\t\t    %s\n" "$(pcs)"
printf "\n"
