#!/usr/bin/env bash

# Wrapper for amazing software giph by phisch

file="$HOME/Pictures/screenshots/gif_$(date '+%Y-%m-%d%H:%M:%S').gif"
file2="$HOME/Videos/vid_$(date '+%Y-%m-%d%H:%M:%S').mp4"


case $1 in
    "sel")
        giph -y -s -b 4 -c '0.61,0.9,0.75,1' -p 16 $file
        ;;

    "selnp")
        giph -y -s -b 4 -c '0.61,0.9,0.75,1' -p -4 $file
        ;;

    "selmp4")
        giph -y -s -f 30 -b 4 -c '0.61,0.9,0.75,1' -p 16 $file2
        ;;
    
    "selnpmp4")
        giph -y -s -f 30 -b 4 -c '0.61,0.9,0.75,1' -p -4 $file2
        ;;

    *)
        giph -y -g "1920x1080+0+0" $file
        ;;
esac
