#!/bin/bash
img="shot_$(date '+%m%d%H%M%S').png"
file="$HOME/Pictures/screenshots/$img"

if [ "$1" == "sel" ]; then
    slop=$(slop -p 20 -f "%g") || exit 1
    read -r G < <(echo $slop)
    import -window root -crop $G $file
else 
    import -window root $file
fi

notify-send -i $file "Saved as $img"
