#!/bin/bash

file="$HOME/Pictures/screenshots/shot_$(date '+%Y-%m-%d%H:%M:%S').png"

if [ "$1" == "sel" ]; then
    slop=$(slop -p 20 -f "%g") || exit 1
    read -r G < <(echo $slop)
    import -window root -crop $G $file
else 
    import -window root $file
fi
