# Shell variables
# Generated by 'wal'
wallpaper='/home/javacafe01/.config/wpg/wallpapers/r2.png'

# Special
background='#2E3440'
foreground='#8FBCBB'
cursor='#8FBCBB'

# Colors
color0='#2E3440'
color1='#88C0D0'
color2='#BF616A'
color3='#5E81AC'
color4='#EBCB8B'
color5='#A3BE8C'
color6='#D08770'
color7='#E5E9F0'
color8='#4C566A'
color9='#88C0D0'
color10='#BF616A'
color11='#5E81AC'
color12='#EBCB8B'
color13='#A3BE8C'
color14='#D08770'
color15='#8FBCBB'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
