#! /bin/sh

### Bspwm Config ###

# Workspaces
bspc monitor -d 1 2 3 4 5

# Window Settings

#~/.bin/wm.bspwm_singles 1 & 

bspc config border_width 	     0
bspc config window_gap           15

# Colors
bspc config focused_border_color  "#5e81ac"
bspc config normal_border_color   "#232730" 
bspc config presel_feedback_color "#4C4C4C"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

### Window Rules ###

bspc rule -a "Zoom Group Chat" state=floating

### Autostart Apps ###

# Handles Keys
sxhkd -c ~/.config/bspwm/sxhkdrc &

# Power Manager
xfce4-power-manager &

# Restore Xresources
xrdb -load ~/.Xresources &

# Background
#~/.bin/wm.bspwm_blur_background &
nitrogen --restore &

# Enables Windows Key
ksuperkey &

# Compositor
picom --dbus &

# Polybar
~/.config/polybar/launch.sh &

# Network Manager
# nm-applet &

# Handles cursor problem
xsetroot -cursor_name left_ptr &

# Load Bitmap Fonts
xset +fp ~/.local/share/fonts &
xset fp rehash &
