#! /bin/sh

### Bspwm Config ###

# Workspaces
bspc monitor -d 1 2 3 4 5

# Window Settings
bspc config border_width        3
bspc config window_gap          0 # 15
bspc config focused_border_color "#607d8b"
bspc config normal_border_color "#2E3440"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
### Window Rules ###
bspc rule -a "Zoom Group Chat" state=floating

### Autostart Apps ###

# Handles Keys
sxhkd &

# Power Manager
xfce4-power-manager &

# Restore Xresources
xrdb -load ~/.Xresources &

# Background
~/bin/blur-background.sh &

# Enables Windows Key
ksuperkey &

# Compositor
picom &

# Polybar
~/.config/polybar/launch.sh &

# Network Manager
# nm-applet &

# Handles cursor problem
xsetroot -cursor_name left_ptr &
