#! /bin/sh

### Bspwm Config ###

# Workspaces
bspc monitor -d 1 2 3 4 5

# Window Settings

~/bin/handle_borders.sh & # This script eliminates borders with one window

bspc config window_gap          0 # 15
bspc config focused_border_color "#5e81ac"
bspc config normal_border_color  "#434C5E"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

### Window Rules ###

bspc rule -a "Zoom Group Chat" state=floating

### Autostart Apps ###

# Handles Keys
sxhkd &

# Power Manager
xfce4-power-manager &

# Restore Xresources
xrdb -load ~/.Xresources &

# Background
#~/bin/blur-background.sh &
nitrogen --restore &

# Enables Windows Key
ksuperkey &

# Compositor
picom --experimental-backends &

# Polybar
~/.config/polybar/launch.sh &

# Network Manager
# nm-applet &

# Handles cursor problem
xsetroot -cursor_name left_ptr &

# Load Bitmap Fonts
xset +fp ~/.local/share/fonts &
xset fp rehash &
