#!/usr/bin/env bash

# Lock command for lockscreen (requires i3lock)

filepath=$(awesome-client 'gears = require("gears"); return gears.filesystem.get_configuration_dir()' | sed 's/\<string\>//g')

trim=$(echo $filepath)

quote_remove=$(echo "${trim:1:-1}")

source "$quote_remove/configs/i3lockrc"

blank=33000000

khl="$($quote_remove/scripts/colorctl -o -$delta -h ${rc:0:6})${rc: -2}"
bshl="$($quote_remove/scripts/colorctl -o +$delta -h ${rc:0:6})${rc: -2}"

i3lock --blur $blur \
	   --verifsize=16 \
	   --veriftext="..." \
	   --radius $radius \
	   --ring-width $width \
	   --indicator --clock \
	   --timesize=$timesize \
	   --datesize=$datesize \
	   --timestr="%I:%M" \
	   --datestr="%B %d, %Y" \
	   --linecolor=$blank \
	   --insidecolor=$ic --ringcolor=$rc \
	   --datecolor=$tc --timecolor=$tc \
	   --separatorcolor=$rc --keyhlcolor=${khl#\#} \
	   --bshlcolor=${bshl#\#} \
	   --verifcolor=$tc --wrongcolor=$tc \
	   --ringvercolor=${rvc:-$rc} --ringwrongcolor=$wc \
	   --insidevercolor=$ic --insidewrongcolor=$ic \
